### ISSUE TITLE
base16Scheme expected a set but found a string error

### ISSUE THREAD

**Issue by niksingh710** [danth/stylix#502]
using the config 
```nix
{ pkgs, config, ... }: {
  stylix = {
    enable = true;
    autoEnable = true;
    # image = ../../wall.png;
    # base16Scheme = "${pkgs.base16-schemes}/share/themes/decaf.yaml";
    image = config.lib.stylix.pixel "base0A";
    base16Scheme = "${pkgs.base16-schemes}/share/themes/catppuccin-latte.yaml";
    polarity = "dark";
    opacity = {
      terminal = 0.8;
      popups = 0.8;
    };
  };
}
```
throws error for `base16Scheme` saying 
```
error: expected a set but found a string with context: "/nix/store/n8mxqgc5g4np5whkr8nvkmzz0pfvdaac-base16-schemes-unstable-2024-06-21/share/themes/catppuccin-latte.yaml"
```

**Comment by trueNAHO** [comment]
> ```nix
>     base16Scheme = "${pkgs.base16-schemes}/share/themes/catppuccin-latte.yaml";
> ```
>
> [...]
>
> throws error for `base16Scheme` saying
>
> ```
> error: expected a set but found a string with context: "/nix/store/n8mxqgc5g4np5whkr8nvkmzz0pfvdaac-base16-schemes-unstable-2024-06-21/share/themes/catppuccin-latte.yaml"
> ```

That's weird because the testbeds use the same value:

https://github.com/danth/stylix/blob/5853f1a8bd072f2ebabfc3de3973084353cf6f1e/stylix/testbed.nix#L91

Maybe the `base16Scheme` `type` definition is wrong:

https://github.com/danth/stylix/blob/5853f1a8bd072f2ebabfc3de3973084353cf6f1e/stylix/palette.nix#L103-L117

For reference, the documentation uses the following dummy values:

https://github.com/danth/stylix/blob/5853f1a8bd072f2ebabfc3de3973084353cf6f1e/docs/settings.nix#L7-L24

**Comment by niksingh710** [comment]
`    base16Scheme = "${pkgs.base16-schemes}/share/themes/catppuccin-latte.yaml";`
this returns a yaml string
```yaml
system: "base16"
name: "Decaf"
author: "Alex Mirrington (https://github.com/alexmirrington)"
variant: "dark"
palette:
  base00: "2d2d2d"
  base01: "393939"
  base02: "515151"
  base03: "777777"
  base04: "b4b7b4"
  base05: "cccccc"
  base06: "e0e0e0"
  base07: "ffffff"
  base08: "ff7f7b"
  base09: "ffbf70"
  base0A: "ffd67c"
  base0B: "beda78"
  base0C: "bed6ff"
  base0D: "90bee1"
  base0E: "efb3f7"
  base0F: "ff93b3"
```

Either `base16Scheme` needs to accept this from its type definition, or it should extract the `palette` and convert it to a nix attribute.

In both the cases, stylix should also change the tips and tricks doc.
I guess a simple solution would be `yaml -> nix attribute`
