### ISSUE TITLE
ci: add binary cache

### ISSUE THREAD

**Issue by brckd** [danth/stylix#880]
I noticed that especially testbeds take a long time to build. This could be avoided by caching build results. There was a Magic Cache before, but it was removed in #745 because it was deprecated. Feel free to suggest and discuss various solutions.

**Comment by brckd** [comment]
I recently tried out a private **Cachix** cache [in my own configuration](https://github.com/brckd/nixdots/blob/ad0aac52ed5fd6e75ee031b550978d263d1f37ef/.github/workflows/cachix.yml) and can recommend it. I'm not aware of any rate limits and as an added benifit it can also be used in local builds.

The following steps would need to be added to jobs in order to be cached.
```yaml
      - name: Install Nix
        uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Set up Cachix
        uses: cachix/cachix-action@v14
        with:
          name: stylix
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Builds to be cached
        run: nix build .\#whatever
```

The `stylix.cachix.org` cache could then be added to `nixConfig.substituters` or `nixConfig.extra-substituters` to use it for both automated and local builds. The same entry could be added to other configurations that use Stylix for the same benifits.
